// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoTecWebAspNetCore.Models;

namespace ProjetoTecWebAspNetCore.Migrations
{
    [DbContext(typeof(AppContextModel))]
    [Migration("20181122170236_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.BalancoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContaID");

                    b.Property<DateTime>("Data");

                    b.Property<string>("TipoGasto");

                    b.Property<double>("Valor");

                    b.HasKey("ID");

                    b.HasIndex("ContaID");

                    b.ToTable("Balanco");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.ContaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumeroConta");

                    b.Property<int>("UsuarioID");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.ConversaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Horiario");

                    b.Property<int>("IdUsuario");

                    b.Property<string>("Mensagem");

                    b.Property<int?>("UsuarioID");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.EmprestimoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Autorizacao");

                    b.Property<DateTime>("Horario");

                    b.Property<int>("IDInvestidor");

                    b.Property<int>("IDTomador");

                    b.Property<int?>("InvestidorID");

                    b.Property<double>("Parcela");

                    b.Property<int>("QuantidadeParcela");

                    b.Property<int?>("TomadorID");

                    b.Property<double>("Valor");

                    b.HasKey("ID");

                    b.HasIndex("InvestidorID");

                    b.HasIndex("TomadorID");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.UsuarioModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Obs");

                    b.Property<string>("Senha");

                    b.Property<string>("TipoUsuario");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.BalancoModel", b =>
                {
                    b.HasOne("ProjetoTecWebAspNetCore.Models.ContaModel", "Conta")
                        .WithMany("Balanco")
                        .HasForeignKey("ContaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.ContaModel", b =>
                {
                    b.HasOne("ProjetoTecWebAspNetCore.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.ConversaModel", b =>
                {
                    b.HasOne("ProjetoTecWebAspNetCore.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID");
                });

            modelBuilder.Entity("ProjetoTecWebAspNetCore.Models.EmprestimoModel", b =>
                {
                    b.HasOne("ProjetoTecWebAspNetCore.Models.UsuarioModel", "Investidor")
                        .WithMany()
                        .HasForeignKey("InvestidorID");

                    b.HasOne("ProjetoTecWebAspNetCore.Models.UsuarioModel", "Tomador")
                        .WithMany()
                        .HasForeignKey("TomadorID");
                });
#pragma warning restore 612, 618
        }
    }
}
